# Generated by Django 3.2.4 on 2024-12-20 12:05

from django.db import migrations, models
import django.db.models.deletion
import inventory.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/items/')),
                ('description', models.TextField()),
                ('user_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('biaya_pesan', models.IntegerField(default=None, null=True)),
                ('lead_time', models.IntegerField(default=None, null=True)),
                ('type', models.CharField(choices=[('mentah', 'MENTAH'), ('jadi', 'JADI')], default=inventory.utils.ItemTypes['MENTAH'], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/items/')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('biaya_pesan', models.IntegerField(default=None, null=True)),
                ('lead_time', models.IntegerField(default=None, null=True)),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('pcs', 'PCS'), ('meter', 'METER'), ('yard', 'YARD'), ('liter', 'LITER'), ('gram', 'GRAM')], default=inventory.utils.UnitTypes['KG'], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outlets',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('price', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('pcs', 'PCS'), ('meter', 'METER'), ('yard', 'YARD'), ('liter', 'LITER'), ('gram', 'GRAM')], default=inventory.utils.UnitTypes['KG'], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.outlet')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('pcs', 'PCS'), ('meter', 'METER'), ('yard', 'YARD'), ('liter', 'LITER'), ('gram', 'GRAM')], default=inventory.utils.UnitTypes['KG'], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.outlet')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(choices=[('purchase', 'PURCHASE'), ('sales', 'SALES')], default=inventory.utils.TypeTypes['PURCHASE'], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.outlet')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchase')),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.sales')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.outlet')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('pcs', 'PCS'), ('meter', 'METER'), ('yard', 'YARD'), ('liter', 'LITER'), ('gram', 'GRAM')], default=inventory.utils.UnitTypes['KG'], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.outlet')),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.outlet')),
            ],
            options={
                'db_table': 'productions',
            },
        ),
    ]
