# Generated by Django 3.2.4 on 2024-12-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20241220_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='outlet_id',
            new_name='outlet',
        ),
    ]
