# Generated by Django 3.2.4 on 2024-12-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_outlet_id_employee_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
