# Generated by Django 3.2.4 on 2024-12-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='outlet',
        ),
        migrations.AddField(
            model_name='employee',
            name='outlet',
            field=models.ManyToManyField(blank=True, related_name='employees', to='inventory.Outlet'),
        ),
    ]
