# Generated by Django 3.2.4 on 2024-12-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20241220_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='outlet',
        ),
        migrations.AddField(
            model_name='employee',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.outlet'),
        ),
    ]
