# Generated by Django 3.2.4 on 2024-12-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20241220_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
