# Generated by Django 3.2.4 on 2024-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_transaction_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
