# Generated by Django 3.2.4 on 2025-03-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stock_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('lead_time', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.outlet')),
            ],
            options={
                'db_table': 'outlet_items',
                'unique_together': {('outlet', 'item')},
            },
        ),
    ]
