# Generated by Django 3.2.4 on 2025-07-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_outletitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_buyer', to='inventory.outlet'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_outlet', to='inventory.outlet'),
        ),
    ]
